ALTER TABLE BUDGET_REVISED_DETAIL_COSTS 
	ALTER COLUMN CostVal decimal(18,4) NULL
GO

ALTER TABLE BUDGET_TOCOMPLETION_DETAIL
	ALTER COLUMN HoursVal decimal(18,4) NULL
GO

ALTER TABLE BUDGET_TOCOMPLETION_DETAIL
	ALTER COLUMN SalesVal decimal(18,4) NULL
GO

ALTER TABLE BUDGET_TOCOMPLETION_DETAIL_COSTS 
	ALTER COLUMN CostVal decimal(18,4) NULL
GO