CREATE NONCLUSTERED INDEX IX_ANNUAL_BUDGET_DATA_DETAILS_COSTS ON dbo.ANNUAL_BUDGET_DATA_DETAILS_COSTS
	(
	IdImport DESC
	) WITH FILLFACTOR = 90 ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX IX_ANNUAL_BUDGET_DATA_DETAILS_HOURS ON dbo.ANNUAL_BUDGET_DATA_DETAILS_HOURS
	(
	IdImport DESC
	) WITH FILLFACTOR = 90 ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX IX_ANNUAL_BUDGET_DATA_DETAILS_SALES ON dbo.ANNUAL_BUDGET_DATA_DETAILS_SALES
	(
	IdImport DESC
	) WITH FILLFACTOR = 90 ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX IX_ANNUAL_BUDGET_IMPORT_DETAILS ON dbo.ANNUAL_BUDGET_IMPORT_DETAILS
	(
	IdImport
	) WITH FILLFACTOR = 90 ON [PRIMARY]
GO


ALTER TABLE dbo.ANNUAL_BUDGET_DATA_DETAILS_HOURS
	DROP CONSTRAINT PK_ANNUAL_BUDGET_DATA_DETAILS
GO
ALTER TABLE dbo.ANNUAL_BUDGET_DATA_DETAILS_HOURS ADD CONSTRAINT
	PK_ANNUAL_BUDGET_DATA_DETAILS_HOURS PRIMARY KEY CLUSTERED 
	(
	IdProject,
	IdPhase,
	IdWorkPackage,
	IdCostCenter,
	YearMonth,
	IdCountry,
	IdAccount
	) WITH FILLFACTOR = 90 ON [PRIMARY]

GO
