BEGIN TRANSACTION
CREATE NONCLUSTERED INDEX IX_EXCHANGE_RATES_CURRENCY_YEARMONTH ON dbo.EXCHANGE_RATES
	(
	YearMonth,
	IdCurrencyTo
	) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX IX_EXCHANGE_RATES_CURRENCY ON dbo.EXCHANGE_RATES
	(
	IdCurrencyTo
	) ON [PRIMARY]
GO
COMMIT