BEGIN TRANSACTION

ALTER TABLE dbo.ACTUAL_DATA_DETAILS_HOURS
	DROP CONSTRAINT FK_ACTUAL_DATA_DETAIL_HOURS_IMPORTS
GO

ALTER TABLE dbo.ACTUAL_DATA_DETAILS_HOURS
	DROP CONSTRAINT FK_ACTUAL_DATA_DETAILS_ASSOCIATES
GO

ALTER TABLE dbo.ACTUAL_DATA_DETAILS_HOURS
	DROP CONSTRAINT FK_ACTUAL_DATA_DETAILS_WORK_PACKAGES
GO

ALTER TABLE dbo.ACTUAL_DATA_DETAILS_HOURS
	DROP CONSTRAINT FK_ACTUAL_DATA_DETAILS_GL_ACCOUNTS
GO

ALTER TABLE dbo.ACTUAL_DATA_DETAILS_HOURS
	DROP CONSTRAINT FK_ACTUAL_DATA_DETAILS_COST_CENTERS
GO

ALTER TABLE dbo.ACTUAL_DATA_DETAILS_HOURS
	DROP CONSTRAINT FK_ACTUAL_DATA_DETAILS_ACTUAL_DATA
GO

CREATE TABLE dbo.Tmp_ACTUAL_DATA_DETAILS_HOURS
	(
	IdProject int NOT NULL,
	IdPhase int NOT NULL,
	IdWorkPackage int NOT NULL,
	IdCostCenter int NOT NULL,
	YearMonth int NOT NULL,
	IdAssociate int NOT NULL,
	IdCountry int NOT NULL,
	IdAccount int NOT NULL,
	HoursQty decimal(12, 2) NOT NULL,
	HoursVal decimal(18, 2) NOT NULL,
	DateImport smalldatetime NOT NULL,
	IdImport int NOT NULL
	)  ON [PRIMARY]
GO
IF EXISTS(SELECT * FROM dbo.ACTUAL_DATA_DETAILS_HOURS)
	 EXEC('INSERT INTO dbo.Tmp_ACTUAL_DATA_DETAILS_HOURS (IdProject, IdPhase, IdWorkPackage, IdCostCenter, YearMonth, IdAssociate, IdCountry, IdAccount, HoursQty, HoursVal, DateImport, IdImport)
		SELECT IdProject, IdPhase, IdWorkPackage, IdCostCenter, YearMonth, IdAssociate, IdCountry, IdAccount, CONVERT(decimal(12, 2), HoursQty), HoursVal, DateImport, IdImport FROM dbo.ACTUAL_DATA_DETAILS_HOURS (HOLDLOCK TABLOCKX)')
GO
DROP TABLE dbo.ACTUAL_DATA_DETAILS_HOURS
GO
EXECUTE sp_rename N'dbo.Tmp_ACTUAL_DATA_DETAILS_HOURS', N'ACTUAL_DATA_DETAILS_HOURS', 'OBJECT'
GO
ALTER TABLE dbo.ACTUAL_DATA_DETAILS_HOURS ADD CONSTRAINT
	PK_ACTUAL_DATA_DETAILS PRIMARY KEY CLUSTERED 
	(
	IdProject,
	IdPhase,
	IdWorkPackage,
	IdCostCenter,
	YearMonth,
	IdAssociate,
	IdCountry,
	IdAccount
	) ON [PRIMARY]

GO
ALTER TABLE dbo.ACTUAL_DATA_DETAILS_HOURS WITH NOCHECK ADD CONSTRAINT
	FK_ACTUAL_DATA_DETAILS_ACTUAL_DATA FOREIGN KEY
	(
	IdProject
	) REFERENCES dbo.ACTUAL_DATA
	(
	IdProject
	)
GO
ALTER TABLE dbo.ACTUAL_DATA_DETAILS_HOURS WITH NOCHECK ADD CONSTRAINT
	FK_ACTUAL_DATA_DETAILS_COST_CENTERS FOREIGN KEY
	(
	IdCostCenter
	) REFERENCES dbo.COST_CENTERS
	(
	Id
	)
GO
ALTER TABLE dbo.ACTUAL_DATA_DETAILS_HOURS WITH NOCHECK ADD CONSTRAINT
	FK_ACTUAL_DATA_DETAILS_GL_ACCOUNTS FOREIGN KEY
	(
	IdCountry,
	IdAccount
	) REFERENCES dbo.GL_ACCOUNTS
	(
	IdCountry,
	Id
	)
GO
ALTER TABLE dbo.ACTUAL_DATA_DETAILS_HOURS WITH NOCHECK ADD CONSTRAINT
	FK_ACTUAL_DATA_DETAILS_WORK_PACKAGES FOREIGN KEY
	(
	IdProject,
	IdPhase,
	IdWorkPackage
	) REFERENCES dbo.WORK_PACKAGES
	(
	IdProject,
	IdPhase,
	Id
	)
GO
ALTER TABLE dbo.ACTUAL_DATA_DETAILS_HOURS WITH NOCHECK ADD CONSTRAINT
	FK_ACTUAL_DATA_DETAILS_ASSOCIATES FOREIGN KEY
	(
	IdAssociate
	) REFERENCES dbo.ASSOCIATES
	(
	Id
	)
GO
ALTER TABLE dbo.ACTUAL_DATA_DETAILS_HOURS WITH NOCHECK ADD CONSTRAINT
	FK_ACTUAL_DATA_DETAIL_HOURS_IMPORTS FOREIGN KEY
	(
	IdImport
	) REFERENCES dbo.IMPORTS
	(
	IdImport
	)
GO


COMMIT

