IF NOT(EXISTS (SELECT * 
                 FROM INFORMATION_SCHEMA.TABLES 
                 WHERE TABLE_NAME = 'BUDGET_TOCOMPLETION_MOVE_OPERATIONS'))
BEGIN
    CREATE TABLE BUDGET_TOCOMPLETION_MOVE_OPERATIONS
	(
	Id INT PRIMARY KEY IDENTITY,
	IdProject INT NOT NULL FOREIGN KEY REFERENCES PROJECTS(Id),
	IdGeneration INT NOT NULL,
	MoveDateTime DATETIME NOT NULL,
	IdAssociateFrom INT NOT NULL FOREIGN KEY REFERENCES ASSOCIATES(Id),
	IdAssociateTo INT NOT NULL FOREIGN KEY REFERENCES ASSOCIATES(Id),
	IdAssociateMovingBudget INT NOT NULL FOREIGN KEY REFERENCES ASSOCIATES(Id)
	)
END


SELECT * FROM BUDGET_TOCOMPLETION_MOVE_OPERATIONS

IF NOT(EXISTS (SELECT * 
                 FROM INFORMATION_SCHEMA.TABLES 
                 WHERE TABLE_NAME = 'BUDGET_REVISED_MOVE_OPERATIONS'))
BEGIN
	CREATE TABLE BUDGET_REVISED_MOVE_OPERATIONS
	(
	Id INT PRIMARY KEY IDENTITY,
	IdProject INT NOT NULL FOREIGN KEY REFERENCES PROJECTS(Id),
	IdGeneration INT NOT NULL,
	MoveDateTime DATETIME NOT NULL,
	IdAssociateFrom INT NOT NULL FOREIGN KEY REFERENCES ASSOCIATES(Id),
	IdAssociateTo INT NOT NULL FOREIGN KEY REFERENCES ASSOCIATES(Id),
	IdAssociateMovingBudget INT NOT NULL FOREIGN KEY REFERENCES ASSOCIATES(Id)
	)
END

SELECT * FROM BUDGET_REVISED_MOVE_OPERATIONS