DELETE FROM ASSOCIATES WHERE [Id] = 0
GO

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.ACTUAL_DATA_DETAILS ADD CONSTRAINT
	FK_ACTUAL_DATA_DETAILS_ASSOCIATES FOREIGN KEY
	(
	IdAssociate
	) REFERENCES dbo.ASSOCIATES
	(
	Id
	)
GO
COMMIT

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.ASSOCIATES
	DROP CONSTRAINT FK_ASSOCIATES_COUNTRIES
GO
COMMIT
BEGIN TRANSACTION
CREATE TABLE dbo.Tmp_ASSOCIATES
	(
	Id int NOT NULL,
	IdCountry int NOT NULL,
	EmployeeNumber varchar(15) NOT NULL,
	Name varchar(50) NOT NULL,
	InergyLogin varchar(50) NOT NULL,
	IsActive bit NOT NULL,
	PercentageFullTime int NOT NULL,
	IsSubContractor bit NOT NULL
	)  ON [PRIMARY]
GO
IF EXISTS(SELECT * FROM dbo.ASSOCIATES)
	 EXEC('INSERT INTO dbo.Tmp_ASSOCIATES (Id, IdCountry, EmployeeNumber, Name, InergyLogin, IsActive, PercentageFullTime, IsSubContractor)
		SELECT Id, IdCountry, EmployeeNumber, Name, InergyLogin, IsActive, PercentageFullTime, IsSubContractor FROM dbo.ASSOCIATES (HOLDLOCK TABLOCKX)')
GO
ALTER TABLE dbo.IMPORTS
	DROP CONSTRAINT FK_IMPORTS_ASSOCIATES
GO
ALTER TABLE dbo.BUDGET_TOCOMPLETION_STATES
	DROP CONSTRAINT FK_BUDGET_TOCOMPLETION_STATES_ASSOCIATES
GO
ALTER TABLE dbo.BUDGET_TOCOMPLETION_DETAIL
	DROP CONSTRAINT FK_BUDGET_REFORECAST_DETAIL_ASSOCIATES
GO
ALTER TABLE dbo.BUDGET_REVISED_STATES
	DROP CONSTRAINT FK_BUDGET_REVISED_STATES_ASSOCIATES
GO
ALTER TABLE dbo.BUDGET_REVISED_DETAIL
	DROP CONSTRAINT FK_BUDGET_REVISED_DETAIL_ASSOCIATES
GO
ALTER TABLE dbo.BUDGET_INITIAL_STATES
	DROP CONSTRAINT FK_BUDGET_INITIAL_STATES_ASSOCIATES
GO
ALTER TABLE dbo.BUDGET_INITIAL_DETAIL
	DROP CONSTRAINT FK_BUDGET_INITIAL_DETAIL_ASSOCIATES
GO
ALTER TABLE dbo.ASSOCIATE_ROLES
	DROP CONSTRAINT FK_ASSOCIATE_ROLES_ASSOCIATES
GO
ALTER TABLE dbo.ANNUAL_BUDGET_IMPORTS
	DROP CONSTRAINT FK_ANNUAL_BUDGET_IMPORTS_ASSOCIATES
GO
ALTER TABLE dbo.WORK_PACKAGES
	DROP CONSTRAINT FK_WORK_PACKAGES_ASSOCIATES
GO
ALTER TABLE dbo.USER_SETTINGS
	DROP CONSTRAINT FK_USER_SETTINGS_ASSOCIATES
GO
ALTER TABLE dbo.PROJECT_CORE_TEAMS
	DROP CONSTRAINT FK_PROJECT_CORE_TEAMS_ASSOCIATES
GO
ALTER TABLE dbo.ACTUAL_DATA_DETAILS
	DROP CONSTRAINT FK_ACTUAL_DATA_DETAILS_ASSOCIATES
GO
DROP TABLE dbo.ASSOCIATES
GO
EXECUTE sp_rename N'dbo.Tmp_ASSOCIATES', N'ASSOCIATES', 'OBJECT'
GO
ALTER TABLE dbo.ASSOCIATES ADD CONSTRAINT
	PK_ASSOCIATES PRIMARY KEY CLUSTERED 
	(
	Id
	) ON [PRIMARY]

GO
ALTER TABLE dbo.ASSOCIATES ADD CONSTRAINT
	UQ_ASSOCIATES_InergyLogin UNIQUE NONCLUSTERED 
	(
	IdCountry,
	InergyLogin
	) ON [PRIMARY]

GO
ALTER TABLE dbo.ASSOCIATES ADD CONSTRAINT
	UQ_ASSOCIATES_EMPLOYEENUMBER UNIQUE NONCLUSTERED 
	(
	IdCountry,
	EmployeeNumber
	) ON [PRIMARY]

GO
ALTER TABLE dbo.ASSOCIATES WITH NOCHECK ADD CONSTRAINT
	FK_ASSOCIATES_COUNTRIES FOREIGN KEY
	(
	IdCountry
	) REFERENCES dbo.COUNTRIES
	(
	Id
	)
GO
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.ACTUAL_DATA_DETAILS WITH NOCHECK ADD CONSTRAINT
	FK_ACTUAL_DATA_DETAILS_ASSOCIATES FOREIGN KEY
	(
	IdAssociate
	) REFERENCES dbo.ASSOCIATES
	(
	Id
	)
GO
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.PROJECT_CORE_TEAMS WITH NOCHECK ADD CONSTRAINT
	FK_PROJECT_CORE_TEAMS_ASSOCIATES FOREIGN KEY
	(
	IdAssociate
	) REFERENCES dbo.ASSOCIATES
	(
	Id
	)
GO
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.USER_SETTINGS WITH NOCHECK ADD CONSTRAINT
	FK_USER_SETTINGS_ASSOCIATES FOREIGN KEY
	(
	AssociateId
	) REFERENCES dbo.ASSOCIATES
	(
	Id
	)
GO
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.WORK_PACKAGES WITH NOCHECK ADD CONSTRAINT
	FK_WORK_PACKAGES_ASSOCIATES FOREIGN KEY
	(
	LastUserUpdate
	) REFERENCES dbo.ASSOCIATES
	(
	Id
	)
GO
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.ANNUAL_BUDGET_IMPORTS WITH NOCHECK ADD CONSTRAINT
	FK_ANNUAL_BUDGET_IMPORTS_ASSOCIATES FOREIGN KEY
	(
	IdAssociate
	) REFERENCES dbo.ASSOCIATES
	(
	Id
	)
GO
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.ASSOCIATE_ROLES WITH NOCHECK ADD CONSTRAINT
	FK_ASSOCIATE_ROLES_ASSOCIATES FOREIGN KEY
	(
	IdAssociate
	) REFERENCES dbo.ASSOCIATES
	(
	Id
	)
GO
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.BUDGET_INITIAL_DETAIL WITH NOCHECK ADD CONSTRAINT
	FK_BUDGET_INITIAL_DETAIL_ASSOCIATES FOREIGN KEY
	(
	IdAssociate
	) REFERENCES dbo.ASSOCIATES
	(
	Id
	)
GO
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.BUDGET_INITIAL_STATES WITH NOCHECK ADD CONSTRAINT
	FK_BUDGET_INITIAL_STATES_ASSOCIATES FOREIGN KEY
	(
	IdAssociate
	) REFERENCES dbo.ASSOCIATES
	(
	Id
	)
GO
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.BUDGET_REVISED_DETAIL WITH NOCHECK ADD CONSTRAINT
	FK_BUDGET_REVISED_DETAIL_ASSOCIATES FOREIGN KEY
	(
	IdAssociate
	) REFERENCES dbo.ASSOCIATES
	(
	Id
	)
GO
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.BUDGET_REVISED_STATES WITH NOCHECK ADD CONSTRAINT
	FK_BUDGET_REVISED_STATES_ASSOCIATES FOREIGN KEY
	(
	IdAssociate
	) REFERENCES dbo.ASSOCIATES
	(
	Id
	)
GO
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.BUDGET_TOCOMPLETION_DETAIL WITH NOCHECK ADD CONSTRAINT
	FK_BUDGET_REFORECAST_DETAIL_ASSOCIATES FOREIGN KEY
	(
	IdAssociate
	) REFERENCES dbo.ASSOCIATES
	(
	Id
	)
GO
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.BUDGET_TOCOMPLETION_STATES WITH NOCHECK ADD CONSTRAINT
	FK_BUDGET_TOCOMPLETION_STATES_ASSOCIATES FOREIGN KEY
	(
	IdAssociate
	) REFERENCES dbo.ASSOCIATES
	(
	Id
	)
GO
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.IMPORTS WITH NOCHECK ADD CONSTRAINT
	FK_IMPORTS_ASSOCIATES FOREIGN KEY
	(
	IdAssociate
	) REFERENCES dbo.ASSOCIATES
	(
	Id
	)
GO
COMMIT

DECLARE CountriesCursor CURSOR FAST_FORWARD FOR
SELECT 	Id,
	Code
FROM COUNTRIES

OPEN CountriesCursor

DECLARE @IdCountry INT
DECLARE @CountryCode VARCHAR(3)
DECLARE @IdAssociate INT

FETCH NEXT FROM CountriesCursor
INTO @IdCountry, @CountryCode

WHILE @@FETCH_STATUS = 0
BEGIN
	SELECT 	@IdAssociate = ISNULL(MAX([Id]), 0) + 1
	FROM 	ASSOCIATES
	
	INSERT INTO ASSOCIATES 	(Id, 		IdCountry,  EmployeeNumber, 	   Name, 	 InergyLogin, 	       IsActive, PercentageFullTime, IsSubContractor)
	VALUES			(@IdAssociate,  @IdCountry, @CountryCode+'999999', 'null, null', @CountryCode+'\null', 0, 0, 0)

	FETCH NEXT FROM CountriesCursor
	INTO @IdCountry, @CountryCode
END
CLOSE CountriesCursor
DEALLOCATE CountriesCursor

GO

