if exists (select * from dbo.sysobjects where id = object_id(N'[IMPORT_LOGS_DETAILS_KEYROWS_MISSING]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [IMPORT_LOGS_DETAILS_KEYROWS_MISSING]
GO
CREATE TABLE [IMPORT_LOGS_DETAILS_KEYROWS_MISSING] (
	[IdImport] [int] NOT NULL ,
	[Id] [int] IDENTITY (1, 1) NOT NULL ,
	[IdRow] [int] NOT NULL ,
	[Details] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
	[Module] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	CONSTRAINT [PK_IMPORT_LOGS_DETAILS_KEYROWS_MISSING] PRIMARY KEY  CLUSTERED 
	(
		[IdImport],
		[Id],
		[IdRow]
	)  ON [PRIMARY] ,
	CONSTRAINT [FK_IMPORT_LOGS_DETAILS_KEYROWS_MISSING_IMPORT_DETAILS_KEYROWS_MISSING] FOREIGN KEY 
	(
		[IdImport],
		[IdRow]
	) REFERENCES [IMPORT_DETAILS_KEYROWS_MISSING] (
		[IdImport],
		[IdRow]
	) NOT FOR REPLICATION ,
	CONSTRAINT [FK_IMPORT_LOGS_DETAILS_KEYROWS_MISSING_IMPORT_LOGS] FOREIGN KEY 
	(
		[IdImport]
	) REFERENCES [IMPORT_LOGS] (
		[IdImport]
	)
) ON [PRIMARY]
GO



