begin tran

ALTER TABLE BUDGET_INITIAL_DETAIL_COSTS NOCHECK CONSTRAINT FK_BUDGET_INITIAL_DETAIL_COSTS_BUDGET_INITIAL_DETAIL
update BUDGET_INITIAL_STATES Set IdAssociate = 527 where IdProject = 903
update BUDGET_INITIAL_DETAIL Set IdAssociate = 527 where IdProject = 903
update BUDGET_INITIAL_DETAIL_COSTS Set IdAssociate = 527 where IdProject = 903
ALTER TABLE BUDGET_INITIAL_DETAIL_COSTS CHECK CONSTRAINT FK_BUDGET_INITIAL_DETAIL_COSTS_BUDGET_INITIAL_DETAIL

ALTER TABLE BUDGET_TOCOMPLETION_DETAIL_COSTS NOCHECK CONSTRAINT FK_BUDGET_TOCOMPLETION_DETAIL_COSTS_BUDGET_TOCOMPLETION_DETAIL
ALTER TABLE BUDGET_TOCOMPLETION_DETAIL NOCHECK CONSTRAINT FK_BUDGET_TOCOMPLETION_DETAIL_BUDGET_TOCOMPLETION_PROGRESS

update BUDGET_TOCOMPLETION_STATES Set IdAssociate = 527 where IdProject = 903
update BUDGET_TOCOMPLETION_PROGRESS Set IdAssociate = 527 where IdProject = 903
update BUDGET_TOCOMPLETION_DETAIL Set IdAssociate = 527 where IdProject = 903
update BUDGET_TOCOMPLETION_DETAIL_COSTS Set IdAssociate = 527 where IdProject = 903

ALTER TABLE BUDGET_TOCOMPLETION_DETAIL_COSTS CHECK CONSTRAINT FK_BUDGET_TOCOMPLETION_DETAIL_COSTS_BUDGET_TOCOMPLETION_DETAIL
ALTER TABLE BUDGET_TOCOMPLETION_DETAIL CHECK CONSTRAINT FK_BUDGET_TOCOMPLETION_DETAIL_BUDGET_TOCOMPLETION_PROGRESS


ALTER TABLE BUDGET_REVISED_DETAIL_COSTS NOCHECK CONSTRAINT FK_BUDGET_REVISED_DETAIL_COSTS_BUDGET_REVISED_DETAIL

update BUDGET_REVISED_STATES Set IdAssociate = 527 where IdProject = 903
update BUDGET_REVISED_DETAIL Set IdAssociate = 527 where IdProject = 903
update BUDGET_REVISED_DETAIL_COSTS Set IdAssociate = 527 where IdProject = 903

ALTER TABLE BUDGET_REVISED_DETAIL_COSTS CHECK CONSTRAINT FK_BUDGET_REVISED_DETAIL_COSTS_BUDGET_REVISED_DETAIL

rollback
--commit