/* row counter phrase
select distinct o.name, sum(i.rows) as SumRows from sysindexes i
join sysobjects o
on i.id=o.id
where o.xtype = 'U'
group by o.name
*/

/* generator phrase
select 'DELETE FROM ' + o.name
from sysobjects o
where o.xtype = 'U'
order by name
*/

--actual
DELETE FROM ACTUAL_DATA_DETAIL_COSTS
DELETE FROM ACTUAL_DATA_DETAILS
DELETE FROM ACTUAL_DATA

DELETE FROM IMPORT_LOGS_DETAILS
DELETE FROM IMPORT_LOGS
DELETE FROM IMPORT_DETAILS
DELETE FROM IMPORTS


--annual budget
DELETE FROM ANNUAL_BUDGET_DATA_DETAIL_COSTS
DELETE FROM ANNUAL_BUDGET_DATA_DETAILS
DELETE FROM ANNUAL_BUDGET_IMPORT_LOGS_DETAILS
DELETE FROM ANNUAL_BUDGET_IMPORT_LOGS
DELETE FROM ANNUAL_BUDGET_IMPORT_DETAILS
DELETE FROM ANNUAL_BUDGET_IMPORTS
DELETE FROM ANNUAL_BUDGET

-- initial budget
DELETE FROM BUDGET_INITIAL_DETAIL_COSTS
DELETE FROM BUDGET_INITIAL_DETAIL
DELETE FROM BUDGET_INITIAL_STATES
DELETE FROM BUDGET_INITIAL

--revised budget
DELETE FROM BUDGET_REVISED_DETAIL_COSTS
DELETE FROM BUDGET_REVISED_DETAIL
DELETE FROM BUDGET_REVISED_STATES
DELETE FROM BUDGET_REVISED

--to completion
DELETE FROM BUDGET_TOCOMPLETION_DETAIL_COSTS
DELETE FROM BUDGET_TOCOMPLETION_DETAIL
DELETE FROM BUDGET_TOCOMPLETION_PROGRESS
DELETE FROM BUDGET_TOCOMPLETION_STATES
DELETE FROM BUDGET_TOCOMPLETION

--catalogs
DELETE FROM HOURLY_RATES
DELETE FROM COST_CENTERS
DELETE FROM DEPARTMENTS

DELETE FROM EXCHANGE_RATES

DELETE FROM GL_ACCOUNTS
DELETE FROM INERGY_LOCATIONS

DELETE FROM PROJECT_CORE_TEAMS

DELETE FROM PROJECTS_INTERCO_LAYOUT
DELETE FROM PROJECTS_INTERCO

DELETE FROM WORK_PACKAGES
DELETE FROM PROJECTS
DELETE FROM PROGRAMS
DELETE FROM OWNERS

--associates
DELETE FROM USER_SETTINGS
DELETE FROM ASSOCIATE_ROLES
DELETE FROM ASSOCIATES

DELETE FROM COUNTRIES
DELETE FROM REGIONS

