IF EXISTS (SELECT * FROM dbo.sysobjects WHERE ID = object_id(N'[dbo].[OLAP_DIMENSION_CUR_CODE]') and OBJECTPROPERTY(id, N'IsView') = 1)
DROP VIEW OLAP_DIMENSION_CUR_CODE
GO

CREATE VIEW OLAP_DIMENSION_CUR_CODE
AS

SELECT Id AS CurrencyIdKey,
       Code  AS CurrencyCode
FROM OLAP_CURRENCIES

GO
