IF EXISTS (SELECT * FROM dbo.sysobjects WHERE ID = object_id(N'dbo.OLAP_FACTTABLE_HOURLY_RATES') and OBJECTPROPERTY(id, N'IsView') = 1)
DROP VIEW OLAP_FACTTABLE_HOURLY_RATES
GO

CREATE VIEW OLAP_FACTTABLE_HOURLY_RATES
AS

SELECT TOP 100 PERCENT
	F.Id AS FunctionIdKey,
 	HR.IdCostCenter AS CostCenterIdKey,
	CURR_ALL.Id as CurrencyIdKey,
	HR.YearMonth AS YearMonthKey,
	CAST(HR.HourlyRate * dbo.fnGetExchangeRate(CURR.ID, CURR_ALL.Id, HR.YearMonth) as Decimal(18,2)) AS HourlyRate
FROM HOURLY_RATES HR
INNER JOIN COST_CENTERS CC
	ON HR.IdCostCenter = CC.Id
INNER JOIN INERGY_LOCATIONS IL
	ON CC.IdInergyLocation = IL.Id
INNER JOIN COUNTRIES C
	ON IL.IdCountry = C.Id
INNER JOIN CURRENCIES CURR
	ON C.IdCurrency  =CURR.Id
INNER JOIN DEPARTMENTS D
	ON CC.IdDepartment = D.Id
INNER JOIN FUNCTIONS F
	ON D.IdFunction = F.Id
CROSS JOIN OLAP_CURRENCIES CURR_ALL
ORDER BY HR.YearMonth, CC.Code

GO


