IF EXISTS (SELECT * FROM dbo.sysobjects WHERE ID = object_id(N'[dbo].[OLAP_CURRENCIES_PROGRAM_INTERCO]') and OBJECTPROPERTY(id, N'IsView') = 1)
DROP VIEW OLAP_CURRENCIES_PROGRAM_INTERCO
GO

CREATE VIEW OLAP_CURRENCIES_PROGRAM_INTERCO
AS

SELECT	DISTINCT
 	PRJ.IdProgram 	AS IdProgram,
	C.IdCurrency 	AS IdCurrency
FROM	OLAP_INTERCO_DATA OAD
INNER JOIN PROJECTS PRJ ON
	PRJ.Id = OAD.IdProject
INNER JOIN COST_CENTERS CC ON
	CC.Id = OAD.IdCostCenter
INNER JOIN INERGY_LOCATIONS IL ON
	IL.Id = CC.IdInergyLocation
INNER JOIN COUNTRIES C ON
	C.Id = IL.IdCountry


GO

