IF EXISTS (SELECT * FROM dbo.sysobjects WHERE ID = object_id(N'[dbo].[OLAP_CURRENCIES_PROGRAM_ALLCATEGORIES]') and OBJECTPROPERTY(id, N'IsView') = 1)
DROP VIEW OLAP_CURRENCIES_PROGRAM_ALLCATEGORIES
GO

CREATE VIEW OLAP_CURRENCIES_PROGRAM_ALLCATEGORIES
AS

SELECT	DISTINCT
 	PRJ.IdProgram	AS IdProgram,
	CURR.Id 	AS IdCurrency
FROM	OLAP_ALLCATEGORIES_DATA OAD
INNER JOIN PROJECTS PRJ ON
	PRJ.Id = OAD.IdProject
INNER JOIN COST_CENTERS CC ON
	CC.Id = OAD.IdCostCenter
INNER JOIN INERGY_LOCATIONS IL ON
	IL.Id = CC.IdInergyLocation
INNER JOIN COUNTRIES C ON
	C.Id = IL.IdCountry
INNER JOIN CURRENCIES CURR ON
	CURR.Id = C.IdCurrency

GO

