IF EXISTS (SELECT * FROM dbo.sysobjects WHERE ID = object_id(N'[dbo].[OLAP_DIMENSION_PROJECT_TYPES]') and OBJECTPROPERTY(id, N'IsView') = 1)
DROP VIEW OLAP_DIMENSION_PROJECT_TYPES
GO

CREATE VIEW OLAP_DIMENSION_PROJECT_TYPES
AS


SELECT DISTINCT TOP 100 PERCENT
	PT.Type AS ProjectTypeName,
	PT.Id AS ProjectTypeIdKey,
	OPT.PhaseTypeName AS PhaseType,
	OPT.PhaseTypeId AS PhaseTypeIdKey,
	PT.Rank AS ProjectTypeRank,
	CAST(CWF.IdWorkPackage + CWF.IdPhase * 10000 + CWF.IdProject * 1000000 AS BIGINT) AS WPFullKey
FROM OLAP_COUNTRIES_WP_FROM CWF
INNER JOIN PROJECTS PRJ
	ON CWF.IdProject = PRJ.Id
INNER JOIN PROJECT_TYPES PT
	ON PRJ.IdProjectType = PT.Id
INNER JOIN OLAP_PHASE_TYPE OPT
	ON CWF.IdPhase = OPT.PhaseId
ORDER BY PT.Rank, PhaseTypeIdKey

GO
