INSERT INTO 
	[IMPORT_APPLICATION_TYPES]([Id], [Name])
VALUES(1, 'SAP')

INSERT INTO 
	[IMPORT_APPLICATION_TYPES]([Id], [Name])
VALUES(2, 'MFG')

INSERT INTO 
	[IMPORT_APPLICATION_TYPES]([Id], [Name])
VALUES(3, 'NET')


INSERT INTO 
	[IMPORT_APPLICATION_TYPES]([Id], [Name])
VALUES(4, 'OTH')

GO

