	--Inserts all modules into the schema

	INSERT INTO MODULES 	([Code],[Name])
	VALUES			('ASC','Associate')
	INSERT INTO MODULES 	([Code],[Name])
	VALUES			('CRT','Core Team')
	INSERT INTO MODULES 	([Code],[Name])
	VALUES			('CTC','Cost Center')
	INSERT INTO MODULES 	([Code],[Name])
	VALUES			('CTY','Country')
	INSERT INTO MODULES 	([Code],[Name])
	VALUES			('DEP','Department')
	INSERT INTO MODULES 	([Code],[Name])
	VALUES			('FOL','Follow-Up')
	INSERT INTO MODULES 	([Code],[Name])
	VALUES			('GLA','G/L Account')
	INSERT INTO MODULES 	([Code],[Name])
	VALUES			('HRA','Hourly Rate')
	INSERT INTO MODULES 	([Code],[Name])
	VALUES			('EXR', 'Exchange Rates')
	INSERT INTO MODULES 	([Code],[Name])
	VALUES			('INI','Initial')
	INSERT INTO MODULES 	([Code],[Name])
	VALUES			('INL','Inergy Location')
	INSERT INTO MODULES 	([Code],[Name])
	VALUES			('DLG', 'Data Logs')
	INSERT INTO MODULES 	([Code],[Name])
	VALUES			('OWN','Program Owner')
	INSERT INTO MODULES 	([Code],[Name])
	VALUES			('PRF','Profile')
	INSERT INTO MODULES 	([Code],[Name])
	VALUES			('PRG','Program')
	INSERT INTO MODULES 	([Code],[Name])
	VALUES			('PRJ','Project')
	INSERT INTO MODULES 	([Code],[Name])
	VALUES			('REF','Reforcast')
	INSERT INTO MODULES 	([Code],[Name])
	VALUES			('REG','Region')
	INSERT INTO MODULES 	([Code],[Name])
	VALUES			('REP','Reporting')
	INSERT INTO MODULES 	([Code],[Name])
	VALUES			('REV','Revised')
	INSERT INTO MODULES 	([Code],[Name])
	VALUES			('SEL','Project Selection')
	INSERT INTO MODULES 	([Code],[Name])
	VALUES			('STS','Status')
	INSERT INTO MODULES 	([Code],[Name])
	VALUES			('TIN','Timing & Interco')
	INSERT INTO MODULES 	([Code],[Name])
	VALUES			('TST','Technical Settings')
	INSERT INTO MODULES 	([Code],[Name])
	VALUES			('TYP','Project Type')
	INSERT INTO MODULES 	([Code],[Name])
	VALUES			('UPL','Upload')
	INSERT INTO MODULES 	([Code],[Name])
	VALUES			('UST','User Settings')
	INSERT INTO MODULES 	([Code],[Name])
	VALUES			('WKP','Work Package')
	INSERT INTO MODULES 	([Code],[Name])
	VALUES			('AND','Download')
	INSERT INTO MODULES 	([Code],[Name])
	VALUES			('ANL','Logs')
	INSERT INTO MODULES 	([Code],[Name])
	VALUES			('ANS','Status')
	INSERT INTO MODULES 	([Code],[Name])
	VALUES			('ANU','Upload')
	INSERT INTO MODULES 	([Code],[Name])
	VALUES			('EXT','Extract')
	INSERT INTO MODULES 	([Code],[Name])
	VALUES			('EXF','Extract Function')
	INSERT INTO MODULES 	([Code],[Name])
	VALUES			('WPT','Work Package Template')
	
GO

